[package]
name = "syn_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
derivative = "2.2.0"
paste = "1.0"
token = { path = "../token" }
lexer = { path = "../lexer" }
